# Generated by Django 5.2.3 on 2025-07-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_carregister_car_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregister',
            name='email',
            field=models.EmailField(default='sample@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='carregister',
            name='full_name',
            field=models.CharField(default='Sample Name', max_length=100),
        ),
    ]
