# Generated by Django 5.2.3 on 2025-09-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_rental_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='car',
        ),
    ]
