# Generated by Django 5.2.3 on 2025-09-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_remove_rental_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('car_model', models.CharField(max_length=150)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
